### ISSUE TITLE
List all vendor page

### ISSUE THREAD

**Issue by jygh98** [ono-manoa-grindz/ono-manoa-grindz#10]
Do all work for this task in a branch called issue-10

List all vendors on UH Manoa campus -> http://manoa.hawaii.edu/food/
*  vendors come up as individual "cards" and clicking on it should link to a description page
* Vendors have a name, picture, operating hours/locations, menu, ratings

**Comment by shinsa2** [comment]
use 
```
 {Roles.userIsInRole(Meteor.userId(), 'admin') ? (
            <Menu.Item as={NavLink} activeClassName="active" exact to="/admin" key='admin'>Admin</Menu.Item>
        ) : ''}
```
for setting certain things for admin role only
possibly change <Menu.Item/> to <Card.description/> or <Card.Extra/>
change 'exact to' and 'key' values
