### ISSUE TITLE
Team Presentation: Time Management

### ISSUE THREAD

**Issue by jygh98** [ono-manoa-grindz/ono-manoa-grindz#2]
# Refer to <a href="http://courses.ics.hawaii.edu/ics314s19/morea/project-management/experience-team-presentation.html">Experience a team presentation</a>.  Complete the following:

### Following questions to keep in mind:
* How will the team coordinate with each other?
* When is everyone available to meet?
* How will you communicate outside of meetings?

**Comment by cruzjoshua** [comment]
Completed issue-2.
![time management slide](https://user-images.githubusercontent.com/35356169/55444442-29e40780-5552-11e9-997a-7a5414ff9d30.png)
